export * from './allCharactersAreSame';
export * from './insensitiveSplitString';
export * from './lessUnderscore';
export * from './strContains';
export * from './randomString';
export * from './convertTabsInSpaces';
export * from './formatFones';
export * from './formatCourseName';
export * from './makeTabs';
