name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@my-project.iam.gserviceaccount.com"
          service_account_key: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "api-ppgco-v1"
          zone: "us-west4-a"
          ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
          command: |
            source ~/.nvm/nvm.sh
            nvm use 20.10.0
            cd /root/projects/igreen-vault
            git checkout origin main
            git pull origin main
            /bin/bash /root/projects/igreen-vault/api-igreen-back-office/prod/deploy.sh

      # Example of using the output
      - id: "test"
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
